mfv_mis/urls.py
from django.contrib import admin
from django.urls import path, include
from custom_query import urlpatterns as query_view_urls
# from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mis.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('', include('reports.urls')),
    path('', include('export_data.urls')),
    path('api/', include('survey.api_urls')),
    path('application_master/', include('application_master.urls')),
    path('', include('application_master.user_url')),
    path('', include('survey.urls')),
    path('configuration/', include('survey.config_urls')),

    # custom query for internal reference purpose url
    path('', include(query_view_urls)),
]
# + debug_toolbar_urls()
admin.site.site_header = "MFV MIS administration"  

mis/urls.py
from django.conf.urls.static import static
from django.urls import path

from .views import *

app_name = "mis"

urlpatterns = [
    path('', login_view, name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),

    path('task-list/', task_list, name="task-list"),
    path('<slug:slug>/monthly-report/<task_id>/', missionindicator_add, name='mission_add'),
    path('mission_edit/<slug:slug>/<task_id>/<id>/', missionindicator_edit,name='mission_edit'),
    path("ajax-task/<task_id>", task_status_changes, name="submitted_approval"),

    path('project-list/', project_list, name="project-list"),
    path('project-add/', ProjectAdd.as_view(), name='project-add'),
    path('project-edit/<id>/', ProjectUpdate.as_view(), name='project-edit'),

    path("user_listing/", user_listing, name="user_listing"),
    path("user-add/", add_user, name="add_user"),
    path("user-profile/<user_id>/", user_profile, name="user_profile"),
    path("add/map-project/<user_id>/<group_id>/", add_map_project, name="add_map_project"),
    path("user-change-password/<id>/", user_change_password, name="user_change_password"),
    path("user-edit/<id>/", edit_user, name="edit_user"),
    path('ajax-project/', project_list_filter),
    path('ajax/state/<state_id>/', get_district, name="get_district"),
	]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models
from application_master.models import *
from django.contrib.postgres.fields import ArrayField


# Create your models here.
class DashboardSummaryLog(BaseContent):
    #-------------------#
    # Store the history of the dashboard query execution.
    #--------------------#
    log_key = models.CharField(max_length=500, unique=True)
    last_successful_update = models.DateTimeField(blank=True, null=True)
    most_recent_update = models.DateTimeField(blank=True, null=True)
    most_recent_update_status = models.CharField(max_length=2500, blank=True, null=True)
    most_recent_update_time_taken_millis = models.IntegerField(default=0)

    def __str__(self):
        return self.log_key

class DashboardWidgetTypes(BaseContent):
    name = models.CharField(max_length=15,unique=True)

    def __str__(self):
        return self.name

class DashboardIndicatorFilter(BaseContent):
    name = models.CharField(max_length=30,null=True, blank=True)
    slug = models.SlugField('Slug', max_length=60, null=True, blank=True)
    chart_type = models.CharField(max_length=100, choices=(('SW','State wise'), ('TS','Time series')), null=True, blank=True)

    def __str__(self):
        return str(self.name)+' - '+str(self.get_chart_type_display())


class DashboardChartWidgets(BaseContent):
    title = models.CharField(max_length=100)
    stats_title = models.CharField('Statistics title',max_length=100, null=True, blank=True)
    label = models.CharField(max_length=500)
    widgetypes = models.ForeignKey(DashboardWidgetTypes,on_delete=models.DO_NOTHING)
    # userroles = models.ManyToManyField(UserRoles)
    indicator = models.ManyToManyField(DashboardIndicatorFilter,blank=True)
    widgetquery = models.TextField()
    survey_id = models.PositiveIntegerField(default=0)
    chart_type = models.CharField(max_length=100, choices=(('NC','Normal Chart'), ('CC','Comparative Charts'), ('SW','State wise'), ('TS','Time series')), default="NC", null=True, blank=True)
    chart_size = models.CharField(max_length=25, null=True, blank=True)
    chart_header = models.CharField(max_length=250, null=True, blank=True)
    haxis_title = models.CharField(max_length=100, null=True, blank=True)
    vaxis_title = models.CharField(max_length=100, null=True, blank=True)
    query_type = models.CharField(max_length=100, choices=(('ORM','ORM'), ('SQL','SQL'),('SQL_P','SQL with Params')), default="ORM", null=True, blank=True)
    order = models.PositiveIntegerField(default=0)
    slug = models.SlugField('Slug', max_length=60, null=True, blank=True)
    slug_choice = models.CharField(max_length=100, choices=(('R','Report'), ('D','Dashboard')), null=True, blank=True)
    config = models.JSONField(default=dict,blank=True,null=True)
    
    def __str__(self):
        return str(self.title) + '-' + str(self.label)


STATUS_CHOICES = (
    (1, 'Submited for Partner Admin'), # once submitted for approval from app it will goes to parter admin
    (2, 'Submitted for Project In-charge'), # once partner admin reveiwed and submitted to Project In-charge
    (3, 'Submitted for Admin'), # once Project In-charge reveiwed and submitted to MFV admin
    (4, 'Approved'), # once project incharge approved , final status
    (5, 'Rejected'), # when partner admin rejected the record
)
class MonthlyDashboard(BaseContent):
    creation_key = models.CharField(max_length=75, unique=True)
    # month = models.IntegerField('Month(YYYYMM)')
    start_date = models.DateField() 
    end_date = models.DateField() 
    children_covered_uuid = ArrayField(models.CharField(max_length=75, blank=True),)
    children_covered_count = models.IntegerField(default=0)
    school_covered_uuid = ArrayField(models.CharField(max_length=75, blank=True),)
    school_covered_count = models.IntegerField(default=0)
    teachers_train_uuid = ArrayField(models.CharField(max_length=75, blank=True),)
    teachers_train_count = models.IntegerField(default=0)
    children_pres_uuid = ArrayField(models.CharField(max_length=75, blank=True),)
    children_pres_count = models.IntegerField(default=0)
    child_prov_spec_uuid = ArrayField(models.CharField(max_length=75, blank=True),)
    child_prov_spec_count = models.IntegerField(default=0)
    pgp_uuid = ArrayField(models.CharField(max_length=75, blank=True),)
    pgp_count = models.IntegerField(default=0)
    children_reffered_uuid = ArrayField(models.CharField(max_length=75, blank=True),)
    children_reffered_count = models.IntegerField(default=0)
    child_prov_hos_uuid = ArrayField(models.CharField(max_length=75, blank=True),)
    child_prov_hos_count = models.IntegerField(default=0)
    children_adv_uuid = ArrayField(models.CharField(max_length=75, blank=True),)
    children_adv_count = models.IntegerField(default=0)
    children_prov_sgy_uuid = ArrayField(models.CharField(max_length=75, blank=True),)
    children_prov_sgy_count = models.IntegerField(default=0)
    swc_uuid = ArrayField(models.CharField(max_length=75, blank=True),)
    swc_count = models.IntegerField(default=0)
    current_status = models.IntegerField(default=0,choices = STATUS_CHOICES)
    submitted_by = models.ForeignKey(User, on_delete=models.CASCADE,related_name='data_entry_operator',)
    partner_admin = models.ForeignKey(User, on_delete=models.CASCADE,**OPTIONAL,related_name='partner_admin',)
    partner_submitted = models.DateField(**OPTIONAL)
    project_incharge = models.ForeignKey(User, on_delete=models.CASCADE,**OPTIONAL,related_name='project_incharge',)
    project_incharge_submitted = models.DateField(**OPTIONAL)
    partner = models.ForeignKey(Partner, on_delete=models.CASCADE)

    def __str__(self):
        return f"Coverage Data for {self.start_date} to {self.end_date}"

    def get_all_array_fields(self):
        all_arrays = (
            self.children_covered_uuid +
            self.school_covered_uuid +
            self.teachers_train_uuid +
            self.children_pres_uuid +
            self.child_prov_spec_uuid +
            self.pgp_uuid +
            self.children_reffered_uuid +
            self.child_prov_hos_uuid +
            self.children_adv_uuid +
            self.children_prov_sgy_uuid +
            self.swc_uuid
        )
        return {tuple(all_arrays):self.current_status}

class Remarks(BaseContent):
    user = models.ForeignKey(User, on_delete=models.CASCADE, **OPTIONAL)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")
    remark = models.CharField(max_length=500)


class ChartMeta(BaseContent):
    chart_type = models.IntegerField(choices=((1, 'Column Chart'), (2, 'Pie Chart'), 
        (3, 'Table Chart'), (4, 'Bar Chart'), (5, 'Column Stack'), (6, 'Bar Dynamic Chart'), (7, 'Column Dynamic Stack'),(8, 'Card chart'), (9, 'Html Table Chart'),
        (10, 'Line chart'), (12,'Dounut chart'),(13,'Html Table Chart Dynmaic'),(14,'Custom Html Table Chart')), blank=True, null=True, help_text="1=Column Chart, 2=Pie Chart, 3=Table Chart, 4=Bar Chart, 5=Column Stack, 6=Bar Dynamic Chart, 7=Column Dynamic Stack, 8=Card Chart, 9=Geo chart,10=Line chart,11=Progressive Line, 12=Dounut chart")
    chart_slug = models.CharField(
        max_length=500, blank=True, null=True, unique=True)
    page_slug = models.CharField(max_length=500, blank=True, null=True)
    chart_title = models.CharField(max_length=500, blank=True, null=True)
    vertical_axis_title = models.CharField(
        max_length=200, blank=True, null=True)
    horizontal_axis_title = models.CharField(
        max_length=200, blank=True, null=True)
    chart_note = models.TextField(blank=True, null=True)
    chart_tooltip = models.TextField(blank=True, null=True)
    chart_height = models.TextField(
        blank=True, null=True, help_text="Chart height in pixel or %")
    click_handler = models.JSONField(
        blank=True, null=True, help_text="json text to set the handler options: {on_click_handler:function-name, url_template:url with placeholders for chart element(bar/column) key value")
    chart_options = models.JSONField(
        blank=True, null=True, help_text="json text to set the chart options")
    div_class = models.TextField(
        blank=True, null=True, help_text="div class name to be used for the chart container - ex:col-md-6, col-md-12 etc")
    chart_query = models.JSONField(
        blank=True, null=True, help_text="sql query and related filter details as json - with keys sqlquery, filters and etc")
    display_order = models.IntegerField(
        blank=True, null=True, help_text="order in which the charts have to be displayed")
    filter_info = models.JSONField(
        blank=True, null=True, help_text="report filters meta data in json format")

    class Meta:
        verbose_name_plural = "Chart Meta"

    def __str__(self):
        return self.chart_title

templates/survey_forms/activity_dropdown.html
<style>
    .page-title-box {
        padding-bottom: 14px;
    }   


    .select-menu {
        width: 100%;
    }
    .select-menu .select-btn {
    display: flex;
    height: 55px;
    background: #fff;
    padding: 20px;
    font-size: 18px;
    font-weight: 400;
    border-radius: 8px;
    align-items: center;
    cursor: pointer;
    justify-content: space-between;
    box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
    }
    .select-menu .options {
    position: absolute;
    width: 30%;
    overflow-y: auto;
    max-height: 295px;
    padding: 0px;
    margin-top: 10px;
    border-radius: 8px;
    background: #fff;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    animation-name: fadeInDown;
    -webkit-animation-name: fadeInDown;
    animation-duration: 0.35s;
    animation-fill-mode: both;
    -webkit-animation-duration: 0.35s;
    -webkit-animation-fill-mode: both;
    }
    .select-menu .options .option {
    display: flex;
    cursor: pointer;
    border-radius: 8px;
    align-items: center;
    background: #fff;
    }
    .select-menu .options .option:hover {
    background: #f2f2f2;
    }
    .select-menu .options .option i {
    font-size: 25px;
    margin-right: 12px;
    }
    .select-menu .options .option .option-text {
        font-size: 18px;
        color: #333;
        width: 100%;
        padding: 12px 16px;
    }

    .select-btn i {
    font-size: 25px;
    transition: 0.3s;
    }

    .select-menu.active .select-btn i {
    transform: rotate(-180deg);
    }
    .select-menu.active .options {
    display: block;
    opacity: 0;
    z-index: 10;
    animation-name: fadeInUp;
    -webkit-animation-name: fadeInUp;
    animation-duration: 0.4s;
    animation-fill-mode: both;
    -webkit-animation-duration: 0.4s;
    -webkit-animation-fill-mode: both;
    }

    @keyframes fadeInUp {
    from {
        transform: translate3d(0, 30px, 0);
    }
    to {
        transform: translate3d(0, 0, 0);
        opacity: 1;
    }
    }
    @keyframes fadeInDown {
        from {
            transform: translate3d(0, 0, 0);
            opacity: 1;
        }
        to {
            transform: translate3d(0, 20px, 0);
            opacity: 0;
        }
    }
</style>
<div class="select-menu active">
    {% if options_dropdown.count > 0 %}
    <div class="select-btn">
        <a class="sBtn-text" href='#'>Profile</a>
        <i class="bx bx-chevron-down"></i>
    </div>

    <ul class="options">
        
        {% for survey_tags in options_dropdown %}
        {% if survey_tags.id == survey.id %}

        <li class="option">
            <a class="option-text" href='{% if school_creation_key  %}/configuration/list/student-details-3004/{{school_creation_key}}/{{school_name}}/{% else %}/configuration/profile/{{creation_key}}/{% endif %}'>Profile</a>
        </li>
        {% else %}
        <li class="option">
            <a class="option-text" href='/configuration/profile/{{survey_tags.slug}}/{% if school_creation_key %}{{school_creation_key}}{% else %}{{creation_key}}{% endif %}/'>
                {{survey_tags.short_name|default:survey_tags.name}}
            </a>
        </li>
        {% endif %}
        {% endfor %}
        {% endif %}
    </ul>
</div>

<script>
    //Multiple options dropdown
//https://codepen.io/gatoledo1/pen/QWmpWjK

const optionMenu = document.querySelector(".select-menu"),
  selectBtn = optionMenu.querySelector(".select-btn"),
  options = optionMenu.querySelectorAll(".option"),
  sBtn_text = optionMenu.querySelector(".sBtn-text");

selectBtn.addEventListener("click", () =>
  optionMenu.classList.toggle("active")
);

options.forEach((option) => {
  option.addEventListener("click", () => {
    let selectedOption = option.querySelector(".option-text").innerText;
    sBtn_text.innerText = selectedOption;

    optionMenu.classList.remove("active");
  });
});
window.onload = function () {
    {% for survey_tags in options_dropdown %}
        optionMenu.classList.remove("active");
        {% if survey_tags.id == survey.id %}
            sBtn_text.innerText = '{{survey_tags.short_name|default:survey_tags.name}}';
            sBtn_text.href ='#'
        {% endif %}
    {% endfor %}
};
</script>

templates/survey_forms/activity_list.html
{% extends "base.html" %}
{% load urs_tags %}
{% load configuration_tags %}


{% block contents %}
<div class="row">
    <div class="col-md-12">
        <div class="card">
        <div class="card-body">
            <div class="card-header card-header-icon d-flex justify-content-between mb-3" data-background-color="rose">
                <div class="p-1">
                    <div class="d-flex align-items-center">
                        <i class="" style="font-size: 22px;"></i>
                        <h4 class="p-1 card-title" style="position: relative; top: 5px; "> Approval List  </h4>
                    </div>
                </div>
                <div class="p-1 d-flex" style="gap:5px">
                    <a onclick="show_or_hide_filters()">
                        <button class="btn btn-primary btn-just-icon btn-round btn-dribbble btn-sm " style="float:right" data-bs-toggle="tooltip" data-bs-original-title="Filter">
                            <i class="bx bx-filter" style="font-size: 20px;"></i>
                        </button>
                    </a>
                </div>
                

            </div>
            <div class="card-content card_section">
                <div class=" filter_class ">
                    <form action="." method='GET' class="row mb-2 mt-3" >
                    <input type="hidden" name="status" value="{{status}}">
                    <div class="col-md-4" id="div_{{level.code}}">
                        <div class="">
                            <div class="form-group  select_group">
                            <spen>Month </spen>
                                <input type="month"  class="form-control" name="month" id="month" value="{{month}}">
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4" id="div_{{level.code}}">
                        <div class="">
                            <div class="form-group  select_group">
                            <spen>Submitted On </spen>
                                <input type="date"  class="form-control" name="submitted_on" id="submitted_on" value="{{submitted_on}}">
                            </div>
                        </div>
                    </div>
                    {% comment %} <div class="col-md-4" id="div_{{level.code}}">
                        <div class="">
                            <div class="form-group  select_group">
                            <spen>Project </spen>
                                <select class="form-control" data-width="100%" data-style="form-select" name="project" id="project" data-live-search="true">                     
                                    <option value="">Select Project</option>
                                {% for proj in projects %}
                                    <option {% if proj.id|slugify == project %} selected {%endif%} value="{{proj.id}}">{{proj.name}}</option>
                                        {% endfor %}
                                </select>
                            </div>
                        </div>
                    </div> {% endcomment %}
                        
                    <div class="col-md-4" id="div_{{level.code}}">
                        <div class="">
                            <div class="form-group  select_group">
                            <spen>Stage </spen>
                                <select class="form-control" data-width="100%" data-style="form-select" name="approval_status" id="approval_status" data-live-search="true">
                                    <option value="">Select Activity</option>
                                {% for appr_status in approval_status %}
                                    <option {% if appr_status.0|slugify == approval_status_id %} selected {%else%} {%endif%} value="{{appr_status.0}}">{{appr_status.1}}</option>{% endfor %}
                                </select>
                            </div>
                        </div>
                    
                    </div>
                    
                    
                    
                    <div class="col-md-4 row mt-4" >
                        <div class="col-md-2" >
                            <input type="submit" class="btn btn-primary btn-fill btn-rose btn-sm btn-filter" value="Filter"><div class="ripple-container"></div>
                        </div>
                        <div class="col-md-2" >
                            <a href="{{request.path}}">
                                <input type="button" class="btn btn-primary btn-fill btn-rose btn-sm btn-filter" value="Clear"><div class="ripple-container"></div>
                            </a>
                        </div>
                    </div>
                    </form>
                </div>
                <div class="table-responsive width_section">
                    <table id="datatables" class="table table-striped" cellspacing="0" width="100%" style="width:100%">
                        <thead class="table-light" >
                            <th>Partner Name</th>
                            <th> Start Date</th>
                            <th> End Date</th>
                            <th> Submitted By</th>
                            <th> Submitted On</th>
                            <th> Stage</th>
                        </thead>
                        <tbody style="vertical-align: middle;">
                            {% for obj in object_list %}
                            <tr>
                                <td>{{obj.partner.name}}</td>
                                <td>{{obj.start_date|date:'d-m-Y'}}</td>
                                <td>{{obj.end_date|date:'d-m-Y'}}</td>
                                <td>{{obj.submitted_by}}</td>
                                <td>{{obj.created|date:'d-m-Y'}}</td>
                                <td><a  href="../{{obj.id}}/">{{ obj.get_current_status_display|default:"-" }}</a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% include 'survey_forms/pagination.html' %}
                </div>
            </div>
        </div>
        </div>
    </div>

{% endblock %}

{% block extra_javascript %}

    <script>
        function show_or_hide_filters(){
            $('.filter_class').toggle()
        }
        $(document).ready(function() {
            {% comment %} {% if not request.GET.keys or request.GET.keys|length in 1 and 'page' in request.GET.keys %}
                $('.filter_class').hide()
            {% elif 'page' in request.GET.keys or 'status' in request.GET.keys and request.GET.keys|length <= 2  %}
                $('.filter_class').hide()
            {% else %}
                $('.filter_class').show()
            {% endif %} {% endcomment %}
          });
    </script>
{% endblock %}

{% block script %}

{% endblock %}

templates/survey_forms/activity_submition_view.html
{% extends 'base.html' %}
{% load configuration_tags%}
{% load report_tags%}
{% load static %}
{% block contents %}
<div class="row align-items-center">
    <div class="col-xl-12 mx-auto">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <p class="text-dark"><b>Status : </b>{{monthly_data.get_current_status_display|default:"-"}}</p>
                        <p class="text-dark"><b>Partner : </b>{{monthly_data.partner.name}} </p>
                        <p class="text-dark"><b>Start Date : </b>{{monthly_data.start_date|date:"d-m-Y"}}</p>
                        <p class="text-dark"><b>Start Date : </b>{{monthly_data.end_date|date:"d-m-Y"}}</p>
                    </div>
                    <div class="table-responsive width_section">
                      <p class="card-title text-center text-uppercase p-1 mb-1 text-white" style="background-color:#13437e;">Dashboard Data</p>
                      <h5 class="card-title groove bg-warning">  </h5>
                      <table id="datatables" class="table table-striped" cellspacing="0" width="100%" style="width:100%">
                          <thead class="table-light" >
                              <th>Name</th>
                              <th>Count</th>
                          </thead>
                          <tbody style="vertical-align: middle;">
                              {% for label,value in dashboard_data.items %}
                              <tr>
                                  <td>{{label}}</td>
                                  <td>{{value|default:"0"}}</td>
                              </tr>
                              {% endfor %}
                          </tbody>
                      </table>
                    </div>
                    {% if remarks %}
                        <h3 class=" mt-4 ">History</h3>
                        {% for i in remarks %}
                            <div id="change-29469" class="journal has-details">
                            <div id="note-1">
                                <h6 class="border-bottom">
                                <img alt="" title="" class="gravatar" srcset="//www.gravatar.com/avatar/033cb83da4134302ba171c2180d64048?rating=PG&amp;size=48&amp;default=mm 2x" src="//www.gravatar.com/avatar/033cb83da4134302ba171c2180d64048?rating=PG&amp;size=24&amp;default=mm">
                                Updated by {{i.user.username}} on {{i.created|date:"d/m/Y g:i A" }}
                                </h6>
                                <ul class="details">
                                {% comment %} <li>Status changed from <strong>{{i.source_state}}</strong> to <strong>{{i.destination_state}}</strong></li> {% endcomment %}
                                {% if i.remark %}
                                    <li>{{i.remark|safe}}</li>
                                {% endif %}
                                </ul>
                            </div>
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
                {% if role_with_permisson_map|get_item:monthly_data.current_status in user_group %}
                  <div class="row justify-content-end">
                    <div class="col-auto">
                      <button class="btn btn-secondary btn-md"  onclick="location.href = '/dashboard/weekly-dashboard/list/'" >Back</button> 
                      <button type="submit" onclick="Confirm('approve')" class="btn btn-success btn-md">Approve </button> 
                      <button type="submit" onclick="Confirm('reject')" class="btn btn-danger btn-md">Reject </button> 
                    </div>
                  </div>
                {% elif 1 in user_group and request.session.show_submission_popup %} <!-- 1 is for data entry op -->
                    <div class="row justify-content-end">
                        <div class="col-auto">
                        <button type="submit" onclick="Confirm('approve',true)" class="btn btn-success btn-md">Submitted for Approval </button> 
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% comment %} <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script> {% endcomment %}
<style>
    #right_side{
        margin-left: 50%
    }
</style>

<script>
    window.scroll({
    top: 200, 
    left: 0, 
    behavior: 'smooth'
    });
</script>

<script>
  function Confirm(label,sub_for_aproval = false) {
    var input = ''
    var title = 'Are you sure ' +label +' ?'
    if (!sub_for_aproval) {
        input = 'textarea'
        title = title  + ' Please enter the remark.'
    }
    Swal.fire({
        title: title,
        input: input,
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Yes, update it!',
        inputValidator: (value) => {
            if (!value) {
                return 'You need to enter a remark!';
            }
        }
    }).then((result) => {
        if (result.isConfirmed) {
            Swal.fire({
                title: 'Sending Mail...',
                allowEscapeKey: false,
                allowOutsideClick: false,
                showConfirmButton: false,
                onBeforeOpen: () => {
                    Swal.showLoading();
                    $.ajax({
                        url: '/dashboard/weekly-dashboard/{{id}}/',
                        type: 'POST',
                        data: {
                            "user_id": {{request.user.id}},
                            'label': label,
                            'remark': result.value
                        },
                        success: function(response) {
                            Swal.fire({
                                title: response.message,  // Assuming your server returns a JSON object with a 'message' field
                                icon: 'success',
                                showConfirmButton: false,
                                timer: 1500
                            }).then(() => {
                                window.location.href = '/dashboard/weekly-dashboard/list/';
                            });
                        },
                        error: function(xhr, status, error) {
                            Swal.fire({
                                title: 'Error!',
                                text: 'There was an error processing your request. Please try again.',
                                icon: 'error',
                                confirmButtonColor: '#3085d6',
                                confirmButtonText: 'OK'
                            });
                        }
                    });
                }    
            });
        }
    });
}

</script>
{% endblock %}

templates/survey_forms/pagination.html
{% load configuration_tags %}
{% query_transform request as urls %}
<div class="col-md-12">
<div class="page pagination" style="float:right;">

                            <span class="step-links">
                                <ul class="pagination justify-content-end" >
                                    
                                    {% if object_list.has_previous %}
                                    <li class="paginate_button page-item first" id="datatables_first">
                                        <a class="page-link" href="{% if urls %}?{{urls}}&{% else %}?{% endif %}page=1" aria-controls="datatables" data-dt-idx="0" tabindex="0">First</a>
                                    </li>
                                    <li class="paginate_button page-item first " id="datatables_first">
                                        <a class="page-link" href="{% if urls %}?{{urls}}&{% else %}?{% endif %}page={{ object_list.previous_page_number }}" aria-controls="datatables" data-dt-idx="0" tabindex="0">Previous</a>
                                    </li>
                                    {% endif %}
                                    <li class="paginate_button page-item active">
                                        <span class="paginate_button page-item page-link current">
                                        {{ object_list.number }}
                                        </span>
                                    </li>
                                    {% if object_list.has_next %}
                                    <li class="paginate_button page-item first " id="datatables_first">
                                        <a class="page-link" href="{% if urls %}?{{urls}}&{% else %}?{% endif %}page={{ object_list.next_page_number }}" aria-controls="datatables" data-dt-idx="0" tabindex="0">Next</a>
                                    </li>
                                    <li class="paginate_button page-item first " id="datatables_first">
                                        <a class="page-link" href="{% if urls %}?{{urls}}&{% else %}?{% endif %}page={{ object_list.paginator.num_pages }}" aria-controls="datatables" data-dt-idx="0" tabindex="0">Last</a>
                                    </li>
                                    {% endif %}
                                </ul>
                            </span>
                        </div>
                        </div>