dashboard/urls.py
from django.urls import path
from dashboard.views import dashboard,monthly_dashboard_list,dashboard_data_approval,PartnerDistricts,jyot_dashboard

app_name = "dashboard"
urlpatterns = [
    path('', dashboard, name="login"),
    path('d2/', jyot_dashboard, name=""),
    path('weekly-dashboard/list/', monthly_dashboard_list),
    path('weekly-dashboard/<id>/', dashboard_data_approval),
    path('partner-districts/', PartnerDistricts.as_view()),
]

mfv_mis/urls.py
from django.contrib import admin
from django.urls import path, include
from custom_query import urlpatterns as query_view_urls
# from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mis.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('', include('reports.urls')),
    path('', include('export_data.urls')),
    path('api/', include('survey.api_urls')),
    path('application_master/', include('application_master.urls')),
    path('', include('application_master.user_url')),
    path('', include('survey.urls')),
    path('configuration/', include('survey.config_urls')),

    # custom query for internal reference purpose url
    path('', include(query_view_urls)),
]
# + debug_toolbar_urls()
admin.site.site_header = "MFV MIS administration"  

mis/urls.py
from django.conf.urls.static import static
from django.urls import path

from .views import *

app_name = "mis"

urlpatterns = [
    path('', login_view, name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),

    path('task-list/', task_list, name="task-list"),
    path('<slug:slug>/monthly-report/<task_id>/', missionindicator_add, name='mission_add'),
    path('mission_edit/<slug:slug>/<task_id>/<id>/', missionindicator_edit,name='mission_edit'),
    path("ajax-task/<task_id>", task_status_changes, name="submitted_approval"),

    path('project-list/', project_list, name="project-list"),
    path('project-add/', ProjectAdd.as_view(), name='project-add'),
    path('project-edit/<id>/', ProjectUpdate.as_view(), name='project-edit'),

    path("user_listing/", user_listing, name="user_listing"),
    path("user-add/", add_user, name="add_user"),
    path("user-profile/<user_id>/", user_profile, name="user_profile"),
    path("add/map-project/<user_id>/<group_id>/", add_map_project, name="add_map_project"),
    path("user-change-password/<id>/", user_change_password, name="user_change_password"),
    path("user-edit/<id>/", edit_user, name="edit_user"),
    path('ajax-project/', project_list_filter),
    path('ajax/state/<state_id>/', get_district, name="get_district"),
	]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models
from application_master.models import *
from django.contrib.postgres.fields import ArrayField


# Create your models here.
class DashboardSummaryLog(BaseContent):
    #-------------------#
    # Store the history of the dashboard query execution.
    #--------------------#
    log_key = models.CharField(max_length=500, unique=True)
    last_successful_update = models.DateTimeField(blank=True, null=True)
    most_recent_update = models.DateTimeField(blank=True, null=True)
    most_recent_update_status = models.CharField(max_length=2500, blank=True, null=True)
    most_recent_update_time_taken_millis = models.IntegerField(default=0)

    def __str__(self):
        return self.log_key

class DashboardWidgetTypes(BaseContent):
    name = models.CharField(max_length=15,unique=True)

    def __str__(self):
        return self.name

class DashboardIndicatorFilter(BaseContent):
    name = models.CharField(max_length=30,null=True, blank=True)
    slug = models.SlugField('Slug', max_length=60, null=True, blank=True)
    chart_type = models.CharField(max_length=100, choices=(('SW','State wise'), ('TS','Time series')), null=True, blank=True)

    def __str__(self):
        return str(self.name)+' - '+str(self.get_chart_type_display())


class DashboardChartWidgets(BaseContent):
    title = models.CharField(max_length=100)
    stats_title = models.CharField('Statistics title',max_length=100, null=True, blank=True)
    label = models.CharField(max_length=500)
    widgetypes = models.ForeignKey(DashboardWidgetTypes,on_delete=models.DO_NOTHING)
    # userroles = models.ManyToManyField(UserRoles)
    indicator = models.ManyToManyField(DashboardIndicatorFilter,blank=True)
    widgetquery = models.TextField()
    survey_id = models.PositiveIntegerField(default=0)
    chart_type = models.CharField(max_length=100, choices=(('NC','Normal Chart'), ('CC','Comparative Charts'), ('SW','State wise'), ('TS','Time series')), default="NC", null=True, blank=True)
    chart_size = models.CharField(max_length=25, null=True, blank=True)
    chart_header = models.CharField(max_length=250, null=True, blank=True)
    haxis_title = models.CharField(max_length=100, null=True, blank=True)
    vaxis_title = models.CharField(max_length=100, null=True, blank=True)
    query_type = models.CharField(max_length=100, choices=(('ORM','ORM'), ('SQL','SQL'),('SQL_P','SQL with Params')), default="ORM", null=True, blank=True)
    order = models.PositiveIntegerField(default=0)
    slug = models.SlugField('Slug', max_length=60, null=True, blank=True)
    slug_choice = models.CharField(max_length=100, choices=(('R','Report'), ('D','Dashboard')), null=True, blank=True)
    config = models.JSONField(default=dict,blank=True,null=True)
    
    def __str__(self):
        return str(self.title) + '-' + str(self.label)


STATUS_CHOICES = (
    (1, 'Submited for Partner Admin'), # once submitted for approval from app it will goes to parter admin
    (2, 'Submitted for Project In-charge'), # once partner admin reveiwed and submitted to Project In-charge
    (3, 'Submitted for Admin'), # once Project In-charge reveiwed and submitted to MFV admin
    (4, 'Approved'), # once project incharge approved , final status
    (5, 'Rejected'), # when partner admin rejected the record
)
class MonthlyDashboard(BaseContent):
    creation_key = models.CharField(max_length=75, unique=True)
    # month = models.IntegerField('Month(YYYYMM)')
    start_date = models.DateField() 
    end_date = models.DateField() 
    children_covered_uuid = ArrayField(models.CharField(max_length=75, blank=True),)
    children_covered_count = models.IntegerField(default=0)
    school_covered_uuid = ArrayField(models.CharField(max_length=75, blank=True),)
    school_covered_count = models.IntegerField(default=0)
    teachers_train_uuid = ArrayField(models.CharField(max_length=75, blank=True),)
    teachers_train_count = models.IntegerField(default=0)
    children_pres_uuid = ArrayField(models.CharField(max_length=75, blank=True),)
    children_pres_count = models.IntegerField(default=0)
    child_prov_spec_uuid = ArrayField(models.CharField(max_length=75, blank=True),)
    child_prov_spec_count = models.IntegerField(default=0)
    pgp_uuid = ArrayField(models.CharField(max_length=75, blank=True),)
    pgp_count = models.IntegerField(default=0)
    children_reffered_uuid = ArrayField(models.CharField(max_length=75, blank=True),)
    children_reffered_count = models.IntegerField(default=0)
    child_prov_hos_uuid = ArrayField(models.CharField(max_length=75, blank=True),)
    child_prov_hos_count = models.IntegerField(default=0)
    children_adv_uuid = ArrayField(models.CharField(max_length=75, blank=True),)
    children_adv_count = models.IntegerField(default=0)
    children_prov_sgy_uuid = ArrayField(models.CharField(max_length=75, blank=True),)
    children_prov_sgy_count = models.IntegerField(default=0)
    swc_uuid = ArrayField(models.CharField(max_length=75, blank=True),)
    swc_count = models.IntegerField(default=0)
    current_status = models.IntegerField(default=0,choices = STATUS_CHOICES)
    submitted_by = models.ForeignKey(User, on_delete=models.CASCADE,related_name='data_entry_operator',)
    partner_admin = models.ForeignKey(User, on_delete=models.CASCADE,**OPTIONAL,related_name='partner_admin',)
    partner_submitted = models.DateField(**OPTIONAL)
    project_incharge = models.ForeignKey(User, on_delete=models.CASCADE,**OPTIONAL,related_name='project_incharge',)
    project_incharge_submitted = models.DateField(**OPTIONAL)
    partner = models.ForeignKey(Partner, on_delete=models.CASCADE)

    def __str__(self):
        return f"Coverage Data for {self.start_date} to {self.end_date}"

    def get_all_array_fields(self):
        all_arrays = (
            self.children_covered_uuid +
            self.school_covered_uuid +
            self.teachers_train_uuid +
            self.children_pres_uuid +
            self.child_prov_spec_uuid +
            self.pgp_uuid +
            self.children_reffered_uuid +
            self.child_prov_hos_uuid +
            self.children_adv_uuid +
            self.children_prov_sgy_uuid +
            self.swc_uuid
        )
        return {tuple(all_arrays):self.current_status}

class Remarks(BaseContent):
    user = models.ForeignKey(User, on_delete=models.CASCADE, **OPTIONAL)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")
    remark = models.CharField(max_length=500)


class ChartMeta(BaseContent):
    chart_type = models.IntegerField(choices=((1, 'Column Chart'), (2, 'Pie Chart'), 
        (3, 'Table Chart'), (4, 'Bar Chart'), (5, 'Column Stack'), (6, 'Bar Dynamic Chart'), (7, 'Column Dynamic Stack'),(8, 'Card chart'), (9, 'Html Table Chart'),
        (10, 'Line chart'), (12,'Dounut chart'),(13,'Html Table Chart Dynmaic'),(14,'Custom Html Table Chart')), blank=True, null=True, help_text="1=Column Chart, 2=Pie Chart, 3=Table Chart, 4=Bar Chart, 5=Column Stack, 6=Bar Dynamic Chart, 7=Column Dynamic Stack, 8=Card Chart, 9=Geo chart,10=Line chart,11=Progressive Line, 12=Dounut chart")
    chart_slug = models.CharField(
        max_length=500, blank=True, null=True, unique=True)
    page_slug = models.CharField(max_length=500, blank=True, null=True)
    chart_title = models.CharField(max_length=500, blank=True, null=True)
    vertical_axis_title = models.CharField(
        max_length=200, blank=True, null=True)
    horizontal_axis_title = models.CharField(
        max_length=200, blank=True, null=True)
    chart_note = models.TextField(blank=True, null=True)
    chart_tooltip = models.TextField(blank=True, null=True)
    chart_height = models.TextField(
        blank=True, null=True, help_text="Chart height in pixel or %")
    click_handler = models.JSONField(
        blank=True, null=True, help_text="json text to set the handler options: {on_click_handler:function-name, url_template:url with placeholders for chart element(bar/column) key value")
    chart_options = models.JSONField(
        blank=True, null=True, help_text="json text to set the chart options")
    div_class = models.TextField(
        blank=True, null=True, help_text="div class name to be used for the chart container - ex:col-md-6, col-md-12 etc")
    chart_query = models.JSONField(
        blank=True, null=True, help_text="sql query and related filter details as json - with keys sqlquery, filters and etc")
    display_order = models.IntegerField(
        blank=True, null=True, help_text="order in which the charts have to be displayed")
    filter_info = models.JSONField(
        blank=True, null=True, help_text="report filters meta data in json format")

    class Meta:
        verbose_name_plural = "Chart Meta"

    def __str__(self):
        return self.chart_title

mis/models.py
from application_master.models import *

from django.contrib.auth.models import User
from django.db import models
from jsonfield import JSONField
from datetime import date
from datetime import  timedelta


# declare a new model with a name "Task"
class Task(BaseContent):
    STATUS_CHOICES = ((1, 'Pending data entry'), (2, 'Submitted for Partner Admin'),(3, 'Submitted for Project In-charge'), (4, 'Approved'), (5,  'Rejected'))
    name = models.CharField(max_length = 150)
    user = models.ForeignKey(User, on_delete = models.DO_NOTHING)
    project = models.ForeignKey(Project, on_delete = models.DO_NOTHING, blank=True, null=True)
    start_date = models.DateField()
    end_date = models.DateField()
    task_status = models.IntegerField(choices = STATUS_CHOICES, default=1)
    extension_date = models.DateField(blank=True, null=True)
    task_month = models.PositiveIntegerField(default=0)
    task_approval = models.ForeignKey(User, on_delete = models.CASCADE, blank=True, null=True, related_name='task_approval')
    project_in_charge = models.ForeignKey(User, on_delete = models.CASCADE, blank=True, null=True, related_name='project_in_charge')


    

    class Meta:
        verbose_name_plural = "Task"
        ordering = ['-id']

    def __str__(self):
        return self.name

    # function to initialize the model, task list edit mission indicator
    # def get_task(self):
    #     try:
    #         obj =  MissionIndicatorAchievement.objects.get(task = self)
    #     except:
    #         obj = None
    #     return obj

    def get_task(self):
        try:
            t = Task.objects.get(id=self.id)
            obj = MissionIndicatorAchievement.objects.filter(task_id=t.id).last()
            
        except Task.DoesNotExist:
            obj = None
        return obj


# declare a new model with a name "MissionIndicatorAchievement"
class MissionIndicatorAchievement(BaseContent):
    CAMP_OPTION=(
        (1, 'Drivers'),
        (2, 'Truckers'),
        (3, 'Carpenters')
    )
    task = models.ForeignKey(Task, on_delete=models.DO_NOTHING, blank=True, null=True)
    response = JSONField(default=dict)
    number_working_days = models.IntegerField(default=0)
    project_reference_file = models.FileField(upload_to='file/%Y/%m/%d',blank=True, null=True)
    camp_organized = models.IntegerField(choices = CAMP_OPTION, blank=True, null=True)
    class Meta:
        verbose_name_plural = "Mission Indicator Achievement"

    def __str__(self):
        return self.task.name
    
class DataEntryRemark(BaseContent):
    task = models.ForeignKey(Task, on_delete = models.DO_NOTHING, blank=True, null=True)
    user_name = models.ForeignKey(User, on_delete=models.DO_NOTHING, blank=True, null=True)
    remark = models.TextField(blank=True, null=True)
    reject_reason = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        verbose_name_plural = "Data Entry Remark"

    def __str__(self):
        return self.task.name 











    

templates/dashboard/dashboard.html
{% extends "base.html" %}
{% load static %} 
{% block contents %}
{% load dashboard_tags %}

<!--************Chart Script Part*********-->
{% include "dashboard/chart_script.html" %}
<!--**************************************-->
<style>
    .dash_total_row{
        background-color:#b5cbe7!important;
        font-weight: bold!important;
    }
</style>
<br>
 <div class="content-overlay"></div>
   <div class="header-navbar-shadow"></div>
	<div class="content-wrapper">
		<div class="content-body">
			<section id="advanced-search-datatable">
				<div class="row">
					<div class="col-md-12">
						<div class="card">
							<div class="card-header" style="text-align:center">
								{% if page_slug == 'livelihood-dashboard' %}
                                    <h2 style="color: #4d586c; background-color: #d9d9d9;width: 100%;padding: 10px;">Dashboard Livelihood Draft</h2>
								{% endif %}
                                {% if page_slug == 'wash-dashboard' %}
                                    <h2 style="color: #FFFFFF; background-color: #403394;width: 100%;">WASH Dashboard</h2>
								{% endif %}
							</div>
                     {% include "dashboard/dropdown_filter.html" %}
						</div>
					</div>
				</div>
				<div class="row">
					{% for param,value in chcl_dict.items %}
						<input type="hidden" id="{{param}}" name="{{param}}" value="{{value}}" />
					{% endfor %}
					{% for ct in data_html.chart %}
                {% if ct.chart_type == 'CARDCHART' %}
                
                  <div class="col-md-12 col-lg-12 col-sm-12 col-12 mb-0 pb-0">
                    <div class="card d-flex pb-0 mb-0">
                        {%if ct.chart_title|lower != 'blank' %}
                        <div class="card-body row align-items-center d-flex justify-content-center mb-1 pb-0"><h4 class="d-flex justify-content-center mb-2">{{ct.chart_title}} {% if ct.tooltip %}<i class="fa fa-info-circle"data-bs-toggle="tooltip" data-bs-placement="top" title="" data-bs-original-title="{{ct.tooltip}}" ></i>{% endif %}</h4>
                        {% endif %}
                            <div class="{%if ct.chart_title|lower == 'blank' %} card-body {% endif %}row align-items-center d-flex justify-content-center {{ct.div}} pb-0 mb-0">
                            {% for citem in ct.datas %}
                            <div class="{{ct.bx_div|index:forloop.counter0}}">
                                <div class="card d-flex" style="height:{{ct.chart_height}};background-color:{{ct.bx_bg|index:forloop.counter0}}!important">
                                    <div class="card-body text-center d-flex align-content-end flex-column" style="padding-bottom:10px!important">
                                    <h6 class="{{ct.bx_text|index:forloop.counter0}}" style="font-size:0.9rem;">{{citem.0}}</h6>
                                    <h3 class="{{ct.bx_text|index:forloop.counter0}} mt-auto mx-auto mb-0" style="font-size:1.1rem;">{{citem.1}}</h3>
                                    </div>
                                </div>
                            </div>
                            
                            {% endfor %}
                        {%if ct.chart_title|lower != 'blank' %}
                        </div>
                        {% endif %}
                        <span class="text-info " style="margin-top:-20px!important;display:inline-block; margin-left:20px;text-align:left;">{{ct.chart_note|safe}}</span>
                    </div>
                    </div>
                 </div>
                {% elif ct.chart_type == 'HTMLTABLECHART' or ct.chart_type == 'HTMLTABLECHARTDYNAMIC' %}
                <div class="{{ct.div}}">
                    <br>
                    <br>
                    <div class="card">
                    <div class="card-body">
                    {%if ct.chart_title != 'blank'%}
                                    <h4>{{ct.chart_title}}</h4>
                                {%endif%}
                                <div style="overflow-y: auto; max-height: 500px;">
                        <table style="max-height:{{ct.chart_height}};width: 100%;" id="table_chart_{{ct.chart_slug}}" class="table_chart">
                                <thead style="position: sticky;
                                top: 0;">
                                {% for head in ct.headers %}
                                <tr>
                                    {% for hrow in head %}
                                    <th {%if hrow|get_item:'color' != ""  %} style="text-align:center;word-wrap: break-word;background-color:{{hrow|get_item:'color'}};color:{{hrow|get_item:'text_color'}};"{%endif%}{%if hrow|get_item:'colspan' > 0 %} colspan="{{hrow|get_item:'colspan'}}" {% endif %} {%if hrow|get_item:'rowspan' > 0 %} rowspan="{{hrow|get_item:'rowspan'}}" {% endif %} >
                                        {{hrow|get_item:'label'|safe}}
                                    </th>
                                    {% endfor %}
                                </tr>
                                {% endfor %}
                                </thead>
                                <tbody>
                                    {%if ct.datas|length == 0 %}
                                    <tr><td colspan="{{ct.headers.0|length}}"> No Data Found</td></tr>
                                    {% else %}
                                        {% for row in ct.datas %}
                                            <tr {% if forloop.counter|divisibleby:2 %}style="background-color: #EEEEEE;" 
                                            {% endif %} class="{%get_row_class row ct.row_css_class ct.url_columns%}">
                                            {% for item in row %}
                                                {% if forloop.counter in ct.url_columns %}
                                                    {% if item.0 == 0 %}
                                                        <td>{{item.0}}</td>
                                                    {% else %}
                                                        <td>
                                                            <a target="{{ct.chart_name}}_{{forloop.counter}}" style="background-color:{{ct.color_codes|get_item:item.0}}!important" href="{{item.1}}">{{item.0}}</a>{{index}}
                                                        </td>
                                                    {% endif %}
                                                {% else %}
                                                    <td style="background-color:{{ct.color_codes|get_item:item}}!important">{{item|default_if_none:"-"|safe }}</td> 
                                                {% endif %}
                                            {% endfor %}
                                            </tr>
                                        {% endfor %}
                                    {% endif %}
                                </tbody>
                                </table>
                                </div>
                            </div>
                    </div>
                    </div>
                {% elif ct.chart_type != 'CARDCHART' %}
						<div class="{{ct.div}}" >
							<div class="card">
								<div class="card-body">
									{%if ct.chart_title != 'blank'%}
									<div class="card-title">
										{% comment %} <i class="fa fa-info-circle" data-html="true" data-toggle="tooltip" data-placement="top" title="{{ct.tooltip}}" data-original-title=""></i> {% endcomment %}
										<h4>{{ct.chart_title}} {% if ct.tooltip %}<i class="fa fa-info-circle"data-bs-toggle="tooltip" data-bs-placement="top" title="" data-bs-original-title="{{ct.tooltip}}" ></i>{% endif %}</h4>
									</div>
                           {% endif %}
									<div class="row">
										<div class="col-12">
											<div id="{{ct.chart_name}}" style="width:100%;height:{{ct.chart_height}};"></div>
										</div>
										<span style="display:inline-block; margin-left: 20px;">{{ct.chart_note|safe}}</span>
									</div>
								</div>
							</div>	
						</div>
                  {% endif %}
					{% endfor %}
				</div>
			</section>
		</div>
	</div>
   <style>
      th, td {
        padding: 10px;
        text-align: left;
        border: 1px solid #000000;
      }
      th {
        text-align: center;
      }
      .card-header {
       padding: 0.625rem 0rem;
      }
      </style>
      <script>
         // Get all elements with the class "myTable"
         var tables = document.getElementsByClassName("table_chart");
         var pageSlug = "{{ page_slug }}";
         // Loop through each table
         if (pageSlug=='mis-dashbaord'){
         for (var t = 0; t < tables.length; t++) {
             var table = tables[t];
             var cells = table.getElementsByTagName("td");
         
             // Loop through each cell in the table
             for (var i = 0; i < cells.length; i++) {
                 var cell = cells[i];
                 var cellValue = cell.innerHTML.trim(); // Trim whitespace from the cell value
                 var numericValue = parseInt(cellValue); // Parse the integer value
         
                 // Remove '%' character from the numeric value
                 if (cellValue.endsWith('%')) {
                     numericValue = parseInt(cellValue.substring(0, cellValue.length - 1));
                 }

                 if (!isNaN(numericValue)) { // Check if the parsed value is a valid number
                     if (numericValue < 100) {
                         cell.style.backgroundColor = "#90ee90"; // lightgreen color code
                     } else if (numericValue >= 100 && numericValue < 150) {
                         cell.style.backgroundColor = "#add8e6"; // lightblue color code
                     } else {
                         cell.style.backgroundColor = "#f08080"; // lightcoral color code
                     }
                 } else {
                     console.error("Invalid cell value:", cellValue);
                 }
             }
         }
        }
         </script>

{% endblock %}
{% block extra_javascript %}
{% endblock %}

templates/dashboard/dropdown_filter.html
{% load static %}

<div class="card-body"> 
    <div class="card position-relative">
       {% comment %} <p class="text-right position-absolute top-0 end-0 text-muted">Data as on {{mat_view_last_updated|date:'d/m/Y g:iA'}}</p>   {% endcomment %} 
    </div>
	<form action="{{form_url}}" class="form-horizontal" method="POST" id="filters">
        {%csrf_token%}
        <div class="row">
                <div class="filter_class d-flex flex-wrap">
                    <div class="p-1 col-12 col-md-6">
                        <div class="">
                            <div class="form-group label-floating select_group">
                                <span>Financial Year<span class="required"></span></span>
                                <select class="selectpicker select2" data-width="100%" data-style="select-with-transition" name="financial-year" id="id_financialyear" data-live-search="true">
                                    <option value="" disabled>Select Financial Year</option>
                                    {% for fin_year in financial_year_list %}
                                        <option value="{{fin_year}}" {% if selected_items.0|slugify == fin_year|slugify %}selected{% endif %}>{{fin_year}}</option>
                                    {% endfor %}
                                </select>
                            </div> 
                        </div>
                    </div>
                    <div class="p-1 col-12 col-md-6">
                        <div class="">
                            <div class="form-group label-floating select_group">
                                <span>Quarterly Year <span class="required"></span></span>
                                <select class="selectpicker select2" data-width="100%" data-style="select-with-transition" name="quarterly-year" id="id_quarterlyyear" data-live-search="true">
                                    <option value="" disabled>Select Quarterly Year</option>
                                    {% for q_year in quarterly_year_list %}
                                        <option value="{{ q_year }}" {% if selected_items.1|slugify == q_year|slugify %}selected{% endif %}>
                                            {{ q_year }}
                                        </option>
                                    {% endfor %}
                                </select>   
                            </div> 
                        </div>
                    </div>
                    <div class="p-1 col-12 col-md-6">
                        <div class="">
                            <div class="form-group label-floating select_group">
                                <span>Partners<span class="required"></span> 
                                </span>
                                <select class="selectpicker select2 " data-width="100%" data-style="select-with-transition" name="Partner" id="id_partner" data-live-search="true" multiple="multiple">
                                        <option value="" disabled>Select Partner</option>
                                    {% if partnerlist|length == 1 %}
                                        <!-- Automatically select the only option if there's only one item in partner_list -->
                                        <option value="{{ partnerlist.0.id }}" selected>{{ partnerlist.0.name }}</option>
                                    {% else %}
                                        {% for part in partnerlist %}
                                            <option value="{{ part.id }}" {% if part.id|slugify in selected_partner_list %}selected{% endif %}>{{ part.name }}</option>
                                        {% endfor %}
                                    {% endif %}
                                </select>
                            </div> 
                        </div>
                    </div>
                    <div class="p-1 col-12 col-md-6">
                        <div class="">
                            <div class="form-group label-floating select_group">
                                <span>Districts<span class="required"></span> 
                                </span>
                                <select class="selectpicker select2 " data-width="100%" data-style="select-with-transition" name="District" id="id_district" data-live-search="true" multiple="multiple">
                                    <option value="" disabled >Select Districts</option>
                                    {% for dist in districts_list %}
                                        <option value="{{dist.id}}" {% if dist.id|slugify in selected_district_list  %}selected{% endif %}>{{dist.name}}</option>
                                    {% endfor %}
                                </select>
                            </div> 
                        </div>
                    </div>
            <div class="col-lg-4 mt-3">
                <button type="submit" class="btn btn-square btn-success btn-lg float-right">Filter</button>
                <button type="button" id="reset" class="btn btn-square btn-primary btn-lg float-right">Reset</button>
            </div>
        </div>
	</form>
	
</div>
<script type="text/javascript"> 
    /*Resetting the Dropdown selected options while clicking Reset Button*/
    document.addEventListener('DOMContentLoaded', function() {
        $("button[id='reset']").on("click", function(event){
            $('#id_project').val('');
            $('#id_2').val('');
            $('#id_3').val('');
            $('#filters').submit();
        });
    });
    document.addEventListener('DOMContentLoaded', function() {
        $("#id_partner").on('change', function(){
            $.ajax({
               type:"POST",
               url:"/dashboard/partner-districts/",
               dataType: "json",
               data: {'partner_id[]':$("#id_partner").val(),'user_id': '{{request.user.id}}'},
               success: function(d) {
                   if (d.data) {    
                        var res = d.data;
                        $('#id_district').find('option').remove().end();
                        for (i=0;i<res.length;i++) {
                            if(Number('{{request.GET.district}}') == res[i].id){
                                $('<option>', {value : res[i].id}).html(res[i].name).appendTo('#id_district' ).attr('selected', 'selected')
                            }
                            else{
                                $('<option>', {value : res[i].id }).html(res[i].name).appendTo('#id_district');
                            }
                        }
                        $('.selectpicker').selectpicker('refresh')
                    }
                }
            });
        });
        });
    </script>
    